VictoriaMetrics has an URL part in the endpoint definition while Prometheus only has scheme://host:port. Allow both
cruise-control-for-kafka/cruise-control pull request #2120
Opened 2024-02-08 11:58 UTC by SLoeuillet

This PR resolves #1917 .

2024-02-08 16:23 UTC, mhratson requested changes
This also needs to be documented…

2024-02-08 16:23 UTC, mhratson commented on cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/monitor/sampling/prometheus/PrometheusMetricSampler.java
> +                              + "expected schema://host:port[/uri], provided %s", endpoint), ex);
```suggestion
                              + "expected schema://host:port[/path], provided %s", endpoint), ex);
```

2024-12-02 01:43 UTC, jiaorenyu commented
Can we merge it?

2025-12-30 11:34 UTC, debu99 commented
when this can be merged?

2026-08-13 12:56 UTC, closed without merging